<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<!-- 
		 Some parts extratec from Lua.tmLanguage
	 -->
	<key>comment</key>
	<string>MoonScript Syntax: 0.0.1</string>
	<key>fileTypes</key>
	<array>
		<string>moon</string>
	</array>

	<key>name</key>
	<string>MoonScript</string>

	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.lua</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(--)(?!\[\[).*$\n?</string>
			<key>name</key>
			<string>comment.line.double-dash.lua</string>
		</dict>


		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.lua</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.lua</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.lua</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(\d{1,3}|.)</string>
					<key>name</key>
					<string>constant.character.escape.lua</string>
				</dict>
			</array>
		</dict>

		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.lua</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.lua</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.lua</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(\d{1,3}|.)</string>
					<key>name</key>
					<string>constant.character.escape.lua</string>
				</dict>
			</array>
		</dict>

		<dict>
			<key>begin</key>
			<string>(?&lt;!--)\[(=*)\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.lua</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]\1\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.lua</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.other.multiline.lua</string>
		</dict>

		<dict>
			<key>match</key>
			<string>(?&lt;![\d.])\s0x[a-fA-F\d]+|\b\d+(\.\d+)?([eE]-?\d+)?|\.\d+([eE]-?\d+)?</string>
			<key>name</key>
			<string>constant.numeric.lua</string>
		</dict>

		<dict>
			<key>name</key>
			<string>support.constant</string>
			<key>match</key>
			<string>\b[A-Z]\w*\b(?!:)</string>
		</dict>

		<dict>
			<key>name</key>
			<string>keyword.operator</string>
			<key>match</key>
			<string>=&gt;|-&gt;</string>
		</dict>

		<dict>
			<key>match</key>
			<string>\b(and|or|not)\b</string>
			<key>name</key>
			<string>keyword.operator.lua</string>
		</dict>

		<dict>
			<key>match</key>
			<string>[a-zA-Z_]\w*\s*(?=:)</string>
			<key>name</key>
			<string>entity.name.function</string>
		</dict>

		<dict>
			<key>match</key>
			<string>\(|\)</string>
			<key>name</key>
			<string>entity.name.function</string>
		</dict>

		<dict>
			<key>match</key>
			<string>\+|-|%|#|\*|\/|\^|==?|~=|!=|\\|:|,|;|\.|&lt;=?|&gt;=?|(?&lt;!\.)\.{2}(?!\.)</string>
			<key>name</key>
			<string>keyword.operator.lua</string>
		</dict>

		<dict>
			<key>match</key>
			<string>{|}|\[|\]</string>
			<key>name</key>
			<string>storage.modifier</string>
		</dict>

		<dict>
			<key>name</key>
			<string>storage.type.class</string>
			<key>match</key>
			<string>\b(class|extends|super)\b</string>
		</dict>

		<dict>
			<key>name</key>
			<string>keyword.control</string>
			<key>match</key>
			<string>\b(if|then|else|elseif|export|import|from|switch|when|with|using|do|for|in|while|return|local|unless|continue|break)\b</string>
		</dict>

		<dict>
			<key>name</key>
			<string>variable.language</string>
			<key>match</key>
			<string>\b(self)\b</string>
		</dict>

		<dict>
			<key>name</key>
			<string>variable.parameter</string>
			<key>match</key>
			<string>@@?[a-zA-Z_]\w*\b</string>
		</dict>

		<dict>
			<key>name</key>
			<string>constant.language.nil</string>
			<key>match</key>
			<string>\b(nil)\b</string>
		</dict>


		<dict>
			<key>match</key>
			<string>\b(true|false)\b</string>
			<key>name</key>
			<string>constant.language.boolean</string>
		</dict>

		<dict>
			<key>match</key>
			<string>(?&lt;!\.|\\)\b(function|repeat|end)\b(?!\s*:)</string>
			<key>name</key>
			<string>invalid.illegal</string>
		</dict>

		<dict>
			<key>match</key>
			<string>(?&lt;![^.]\.|\\)\b(assert|collectgarbage|dofile|error|getfenv|getmetatable|ipairs|loadfile|loadstring|module|next|pairs|pcall|print|rawequal|rawget|rawset|require|select|setfenv|setmetatable|tonumber|tostring|type|unpack|xpcall)\b</string>
			<key>name</key>
			<string>support.function.lua</string>
		</dict>

		<dict>
			<key>match</key>
			<string>(?&lt;![^.]\.|\\)\b(_G)\b</string>
			<key>name</key>
			<string>support.constant</string>
		</dict>

		<dict>
			<key>match</key>
			<string>(?&lt;![^.]\.|\\)\b(coroutine\.(create|resume|running|status|wrap|yield)|string\.(byte|char|dump|find|format|gmatch|gsub|len|lower|match|rep|reverse|sub|upper)|table\.(concat|insert|maxn|remove|sort)|math\.(abs|acos|asin|atan2?|ceil|cosh?|deg|exp|floor|fmod|frexp|ldexp|log|log10|max|min|modf|pow|rad|random|randomseed|sinh?|sqrt|tanh?)|io\.(close|flush|input|lines|open|output|popen|read|tmpfile|type|write)|os\.(clock|date|difftime|execute|exit|getenv|remove|rename|setlocale|time|tmpname)|package\.(cpath|loaded|loadlib|path|preload|seeall)|debug\.(debug|[gs]etfenv|[gs]ethook|getinfo|[gs]etlocal|[gs]etmetatable|getregistry|[gs]etupvalue|traceback))\b</string>
			<key>name</key>
			<string>support.function.library.lua</string>
		</dict>

	</array>

	<key>scopeName</key>
	<string>source.moonscript</string>
	<key>uuid</key>
	<string>D363822C-639B-4450-A21A-F45643A6940F</string>
</dict>
</plist>
